DOPS-2816: Add iroha2-perf CI
soramitsu/iroha2-perf pull request #28
Opened 2023-11-01 14:45 UTC by BAStos525

## Title
[DOPS-2816]: Implement CI/CD for the new iroha2 longevity testing service

##Changes
1. Add CI workflow file
2. Add `Dockerfile`

## Author
Sign-of by: <zyabkin@soramitsu.co.jp>

2023-11-08 21:28 UTC, C4tWithShell requested changes

2023-11-08 21:28 UTC, C4tWithShell commented on docker-compose.yml
healthchecks, log rotation, restart policy?

2023-11-09 06:26 UTC, BAStos525 commented on docker-compose.yml
See the **NOTE** in PR title. This is a public compose template for common and outside usage. The real compose .j2 file for deployment will be in `iroha-deploy` repo.
This service still is under development and so that we haven't stated a healthcheck yet.

2023-11-09 07:32 UTC, wpi86 requested changes

2023-11-09 07:32 UTC, wpi86 commented on .github/workflows/iroha2-perf-ci.yml
> +      - uses: actions/checkout@v4
pin version with hash on all actions

2023-11-09 07:32 UTC, wpi86 commented on docker-compose.yml
i think we should add this stuff anyway because this is best practice

2023-11-09 12:59 UTC, C4tWithShell approved these changes

2023-11-10 06:06 UTC, wpi86 approved these changes

2023-11-10 06:41 UTC, marat-biriushev approved these changes

2023-11-14 10:19 UTC, Cre-eD approved these changes

2023-11-14 14:52 UTC, merged